### ISSUE TITLE
[DISCUSSION] BUMP validation

### ISSUE THREAD

**Issue by sirdeggen** [bitcoin-sv/ts-sdk#25]
## Summary

During this work: [23](https://github.com/bitcoin-sv/ts-sdk/pull/23) it was discovered that the ChainTracker assumes each merkle root will be looked up individually. The working assumption of the BlockHeaderService was that you'd want to ask it "are all these BUMPs valid?" at the beginning of parsing an inbound transaction. This requires a different approach.

## Motivation
The thinking was that the first thing you receive in BEEF format is the list of BUMPS. You could at that point immediately make a request to validate the data with your ChainTracker while you continue to parse the rest of the inbound transaction data thereafter.

Why do you believe this to be important?

## Description

I suspect that validation could be faster if we reduce the number of round trips needed here to one in every case. This is only important for a hosted ChainTracker, which I assume was not the mindset when this was built. The down side is that you get pass/fail rather than being able to deny that one transaction, and continue working backward through the parents. This approach assumes that you might have ropey data, and that the counterparty sent you more than absolutely necessary, which seems unlikely.

## Additional References

spv-wallet implements it in the parallel way, but I'm keen to keep this issue open for discussion until we define best practice one way or another.

**Comment by ty-everett** [comment]
Perhaps certain chain trackers, depending on how they are implemented, should cache the response for a given merkle root. Then, subsequent checks for this root are essentially instant. There is one round trip to check one root, but subsequent checks for the same root don't require additional round trips.

I'd like to justify a change based on performance numbers, because I suspect that caching would speed things up on its own. It would be a bit tricky to start the recursive parallel validation process on the tree of scripts while the merkle root verification happens in the background, because each node in the tree requires these results before it makes sense to proceed to its parent nodes.

**Comment by ty-everett** [comment]
What do you think of [these changes](https://github.com/bitcoin-sv/ts-sdk/commit/5df05d82c6fd6e99890ae7aba23811e3947b9612), which extend the interface with the ability to verify multiple roots at once? This could be used in the BEEF verification.

**Comment by sirdeggen** [comment]
Sorry to leave this unanswered - it's a good thing to add, but doesn't address my suggestion directly because really it's the validation logic when parsing a BEEF which would need to be updated to take this approach.

No big deal. If validation speed ever becomes a concern, this is an area you could improve performance.
