### ISSUE TITLE
[BUG] `Script.fromASM` return invalid script

### ISSUE THREAD

**Issue by zhfnjust** [bitcoin-sv/ts-sdk#42]
## Bug Description

Briefly describe the bug/issue you've encountered.

## Steps to Reproduce

```ts
import { OP, Script } from "@bsv/sdk";
import assert from "assert";

const s = Script.fromASM("76");


assert.strictEqual(s.toHex(), "0176")
//assert.strictEqual(s.toHex(), "0176")
console.log(s.toHex())
```

## Expected Behavior

`assert.strictEqual(s.toHex(), "0176")` should succeed.

## Actual Behavior

```
AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
+ actual - expected

+ 'OP_PUSHDATA1'
- '0176'
    at assert (c:\Users\myland\code\scryptlib\test\tx.test.ts:7:8)
    at Object.<anonymous> (c:\Users\myland\code\scryptlib\test\tx.test.ts:9:22)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Object.S (C:\Users\myland\AppData\Local\npm-cache\_npx\fd45a72a545557e9\node_modules\tsx\dist\cjs\index.cjs:1:1292)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25) {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: 'OP_PUSHDATA1',
  expected: '0176',
  operator: 'strictEqual'
}

```

## Stack Traces or Screenshots

If applicable, add screenshots or stack traces to help explain the issue.

## Environment

- OS: [e.g. MacOS, Windows]
- Node version: [e.g. 12.20]
- `@bsv/sdk` version: [e.g. 1.2.3]

## Additional Information

Provide any additional context or information about the bug.

**Comment by ty-everett** [comment]
ASM has always had some strange irregularities and ambiguities. There have been different way to represent different things, and the library attempts to create faithful reproductions of scripts to and from assembly language. However, there's no guarantee that an assembly language script will be imported or exported properly.

This is because there's no formal specification for assembly language, at least not one that I could find when the library was being developed. It's mainly there to help people debugging scripts, so they can see what opcodes are being executed. But for deterministic and reproducible representations suitable for serialization and deserialization, I definitely recommend the use of hex or binary formats over using the assembly language.

**Comment by sirdeggen** [comment]
This looks like toHex() is actually doing "toASM()" here. Which is definitely a bug. Attempting to reproduce...

**Comment by sirdeggen** [comment]
Yep turns out toHex returns ASM and toASM returns Hex.

**Comment by sirdeggen** [comment]
Ooft fromHex() is super broken also - probably for the same reason (token matching in the wrong direction)

**Comment by sirdeggen** [comment]
eg. 
```javascript
const s = Script.fromHex("76 98342742059875243 OP_DUP OP_CHECKSIG")
s.toASM()
//> 'OP_DUP OP_LSHIFT 274205987524030NaN0NaN0NaN0cec0NaN0NaN'
```
